---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - name: http
      port: 80
      nodePort: 30080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
#      volumes:
#        - name: config-mount
#          hostPath:
#            path: 
      containers:
        - name: hello
          image: irfantwilio/hello:latest
#          imagePullPolicy: Never
#          command: ['sleep', 'infinity']
          ports:
            - containerPort: 80
#          volumeMounts: # container internal directories
#            - name: config-mount
#              mountPath: /etc/opt/ionic/config
